baseURL = 'https://pwnyz.com/'
languageCode = 'en-us'
title = 'pwnyz'
pygmentsStyle = "monokai"
theme = 'gokarna'

[params]
    avatarURL = "/images/avatar.jpg"
    dateFormat = "02 January 2006"
    numberPostsOnHomePage = 4
    showBackToTopButton = true
    showPostsOnHomePage = "recent"
    enableEmoji = true


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
